name = "纯色背景_文字在下"

[params]
border_ratio = [
    0.0,
    0.03,
    0.0,
    0.0,
]
border_equal = false
position = "Center"
background = [
    255,
    255,
    255,
]
border_radius = 0.0
shadow_size = 0.0
shadow_density = 0.0
solid_background = true
blur_sigma = 15.0
quality = 95

[[text_groups]]
position = "Bottom"
direction = "Horizontal"
align = "Left"
padding = 0.03
time_format = "%Y/%m/%d"

[text_groups.text]
template = ["{Logo} {型号}"]

[[text_groups.text.text_params]]
font = "Arial"
size = 0.03
line_spacing = 1.2999999523162842
italic = false
bold = true
align = "Center"

[[text_groups]]
position = "Bottom"
direction = "Horizontal"
align = "Right"
padding = 0.03
time_format = "%Y/%m/%d"

[text_groups.text]
template = [
    "{拍摄日期} - {区}",
    "{等效焦距}mm f/{光圈} {快门}s ISO{ISO}",
]

[[text_groups.text.text_params]]
font = "Maple Mono NF CN"
size = 0.02200000047683716
line_spacing = 1.2999999523162842
italic = false
bold = false
align = "Right"

[[text_groups.text.text_params]]
font = "Maple Mono NF CN"
size = 0.02200000047683716
line_spacing = 1.2999999523162842
color = [
    87,
    83,
    78,
]
italic = false
bold = false
align = "Right"
